MONSTER_TEMPLATES = [
    {
        "name": "Лесной Гоблин",
        "level": 1,
        "hp": 40,
        "strength": 5,
        "agility": 4,
        "intuition": 3,
        "endurance": 5,
        "damage_min": 2,
        "damage_max": 5,
        "crit_chance": 5,
        "dodge_chance": 5,
        "armor": 2,
        "xp_reward": 50,
        "coin_reward": 10,
    },
    {
        "name": "Дикий Волк",
        "level": 2,
        "hp": 60,
        "strength": 7,
        "agility": 8,
        "intuition": 5,
        "endurance": 6,
        "damage_min": 4,
        "damage_max": 8,
        "crit_chance": 10,
        "dodge_chance": 15,
        "armor": 1,
        "xp_reward": 100,
        "coin_reward": 20,
    },
    {
        "name": "Разъяренный Огр",
        "level": 3,
        "hp": 120,
        "strength": 15,
        "agility": 2,
        "intuition": 2,
        "endurance": 10,
        "damage_min": 8,
        "damage_max": 15,
        "crit_chance": 2,
        "dodge_chance": 0,
        "armor": 5,
        "xp_reward": 250,
        "coin_reward": 50,
    },
]
