# Generated by Django 5.2.2 on 2025-07-29 18:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterinventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='characterinventory',
            name='character',
        ),
        migrations.RemoveField(
            model_name='characterinventory',
            name='item_instance',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='item',
        ),
        migrations.RemoveField(
            model_name='iteminstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='characterprofile',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='characterprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='characterprofile',
            name='stamina_max',
        ),
        migrations.RemoveField(
            model_name='characterprofile',
            name='stamina_remaining',
        ),
        migrations.RemoveField(
            model_name='characterresources',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='characterresources',
            name='gold_dust',
        ),
        migrations.RemoveField(
            model_name='characterresources',
            name='silver',
        ),
        migrations.RemoveField(
            model_name='characterresources',
            name='silver_dust',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='current_hp',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='current_mp',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='hp_regen_percent',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='max_hp',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='max_mp',
        ),
        migrations.RemoveField(
            model_name='characterstats',
            name='mp_regen_percent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_equippable',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_stackable',
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='_classification',
            field=models.CharField(db_column='classification', default=1, editable=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterresources',
            name='current_hp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterresources',
            name='current_mp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterresources',
            name='hp_regen_percent',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='characterresources',
            name='max_hp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterresources',
            name='max_mp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='characterresources',
            name='mp_regen_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='characterwallet',
            name='gold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Золото (гр.)'),
        ),
        migrations.AddField(
            model_name='characterwallet',
            name='gold_dust',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Золотая пыль (гр.)'),
        ),
        migrations.AddField(
            model_name='characterwallet',
            name='silver',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Серебро (гр.)'),
        ),
        migrations.AddField(
            model_name='characterwallet',
            name='silver_dust',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Серебряная пыль (гр.)'),
        ),
        migrations.AlterField(
            model_name='characterprofile',
            name='name',
            field=models.CharField(default='Новый Игрок', max_length=50),
        ),
        migrations.AlterField(
            model_name='playerlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CharacterBattleStats',
        ),
        migrations.DeleteModel(
            name='CharacterInventory',
        ),
        migrations.DeleteModel(
            name='ItemInstance',
        ),
    ]
