# Generated by Django 5.2.2 on 2025-08-15 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('weapon', 'Оружие'), ('armor', 'Броня'), ('jewelry', 'Украшения'), ('potion', 'Зелья'), ('scroll', 'Свитки'), ('misc', 'Разное')], max_length=10)),
                ('subtype', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_stackable', models.BooleanField(default=False)),
                ('max_stack', models.IntegerField(default=1)),
                ('base_price', models.IntegerField(default=0)),
                ('bonus_strength', models.IntegerField(default=0)),
                ('bonus_agility', models.IntegerField(default=0)),
                ('bonus_intuition', models.IntegerField(default=0)),
                ('bonus_endurance', models.IntegerField(default=0)),
                ('bonus_intelligence', models.IntegerField(default=0)),
                ('bonus_wisdom', models.IntegerField(default=0)),
                ('bonus_spirit', models.IntegerField(default=0)),
                ('bonus_phys_damage_min', models.IntegerField(default=0)),
                ('bonus_phys_damage_max', models.IntegerField(default=0)),
                ('bonus_crit_chance', models.FloatField(default=0)),
                ('bonus_dodge_chance', models.FloatField(default=0)),
                ('bonus_shield_block', models.FloatField(default=0)),
                ('bonus_parry', models.FloatField(default=0)),
                ('bonus_counterattack', models.FloatField(default=0)),
                ('bonus_armor_penetration', models.FloatField(default=0)),
                ('bonus_phys_absorption_percent', models.FloatField(default=0)),
                ('bonus_magic_power', models.FloatField(default=0)),
                ('bonus_magic_power_fire', models.FloatField(default=0)),
                ('bonus_magic_power_air', models.FloatField(default=0)),
                ('bonus_magic_power_water', models.FloatField(default=0)),
                ('bonus_magic_power_earth', models.FloatField(default=0)),
                ('bonus_magic_power_light', models.FloatField(default=0)),
                ('bonus_magic_power_dark', models.FloatField(default=0)),
                ('bonus_magic_resist_penetration', models.FloatField(default=0)),
                ('require_level', models.IntegerField(default=0)),
                ('require_strength', models.IntegerField(default=0)),
                ('require_agility', models.IntegerField(default=0)),
                ('require_intuition', models.IntegerField(default=0)),
                ('require_endurance', models.IntegerField(default=0)),
                ('require_intelligence', models.IntegerField(default=0)),
                ('require_wisdom', models.IntegerField(default=0)),
                ('require_spirit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('classification', models.CharField(choices=[('warrior', 'Воин'), ('mage', 'Маг')], max_length=10)),
                ('strength', models.IntegerField(default=10)),
                ('agility', models.IntegerField(default=10)),
                ('intuition', models.IntegerField(default=10)),
                ('endurance', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('spirit', models.IntegerField(default=10)),
                ('current_hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('current_mp', models.IntegerField(default=50)),
                ('max_mp', models.IntegerField(default=50)),
                ('hp_regen_rate', models.FloatField(default=1.0)),
                ('mp_regen_rate', models.FloatField(default=1.0)),
                ('experience', models.IntegerField(default=0)),
                ('experience_to_next_level', models.IntegerField(default=1000)),
                ('coins', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('silver_dust', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('gold_dust', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('varangian_stones', models.IntegerField(default=0)),
                ('magic_coins', models.IntegerField(default=0)),
                ('valknut_tokens', models.IntegerField(default=0)),
                ('ref_coins', models.IntegerField(default=0)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.clan')),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('slot_index', models.IntegerField()),
                ('current_durability', models.IntegerField()),
                ('max_durability', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_money', models.IntegerField(default=0)),
                ('price_silver', models.IntegerField(default=0)),
                ('price_gold', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=-1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
    ]
