# Generated by Django 5.2.2 on 2025-08-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='game_chatme_room_id_c32ae6_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_system',
        ),
    ]
