# Generated by Django 5.2.2 on 2025-08-16 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_chatmessage_options_alter_chatroom_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fire', 'Огонь'), ('water', 'Вода'), ('air', 'Воздух'), ('earth', 'Земля'), ('dark', 'Тьма'), ('light', 'Свет')], max_length=20, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='alliances/')),
                ('bonus_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Совет Девяти', max_length=50, unique=True)),
                ('description', models.TextField(default='Официальный клан модераторов игры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='clan',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ModeratorClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('moderator', 'Модератор'), ('inspector', 'Отдел проверок'), ('leader', 'Глава Клана'), ('gm', 'GM')], max_length=20)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('permissions', models.JSONField(default=dict)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.moderatorclan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='clans/banners/')),
                ('level', models.IntegerField(default=1)),
                ('reputation', models.IntegerField(default=0)),
                ('min_level_to_join', models.IntegerField(default=7)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.alliance')),
            ],
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('member', 'Член'), ('leader', 'Глава')], default='member', max_length=20)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('contribution', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='game.playerclan')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('inspector_notes', models.TextField(blank=True)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='game.playerprofile')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_verifications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClanJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_join_requests', to='game.playerprofile')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='game.playerclan')),
                ('verification_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='game.playerverificationrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Clan',
        ),
    ]
