# Generated by Django 5.2.2 on 2025-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alliance_moderatorclan_remove_playerprofile_clan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TavernItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('first-course', 'Первые блюда'), ('second-course', 'Вторые блюда'), ('salads', 'Салаты'), ('drinks', 'Напитки'), ('desserts', 'Десерты'), ('other', 'Разное')], max_length=20)),
                ('icon', models.CharField(default='🍲', max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('quantity_description', models.CharField(max_length=50)),
                ('hp_restore', models.IntegerField(default=0)),
                ('mp_restore', models.IntegerField(default=0)),
                ('energy_restore', models.IntegerField(default=0)),
                ('max_per_purchase', models.IntegerField(default=10)),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=-1)),
            ],
        ),
    ]
