# Generated by Django 5.2.2 on 2025-08-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_tavernitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavernitem',
            name='image',
        ),
        migrations.AddField(
            model_name='tavernitem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tavernitem',
            name='energy_restore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tavernitem',
            name='icon',
            field=models.CharField(default='🍲', max_length=10),
        ),
        migrations.AlterField(
            model_name='tavernitem',
            name='stock',
            field=models.IntegerField(default=-1),
        ),
    ]
