# Generated by Django 5.2.2 on 2025-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_tavernitem_image_tavernitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavernitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tavernitem',
            name='energy_restore',
        ),
        migrations.RemoveField(
            model_name='tavernitem',
            name='icon',
        ),
        migrations.AddField(
            model_name='tavernitem',
            name='image',
            field=models.ImageField(default=1, upload_to='tavern_items/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tavernitem',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
