# Generated by Django 5.2.2 on 2025-08-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_tavernitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tavernitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tavern_items/'),
        ),
    ]
