# Generated by Django 5.2.2 on 2025-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_tavernitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tavernitem',
            name='image',
            field=models.ImageField(default=1, upload_to='tavern_items/'),
            preserve_default=False,
        ),
    ]
