# Generated by Django 5.2.2 on 2025-08-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_tavernitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavernitem',
            name='quantity_description',
        ),
    ]
