# Generated by Django 5.2.2 on 2025-08-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_adminaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='coins',
            new_name='free_points',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='gold',
            new_name='sub_level',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='gold_dust',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='magic_coins',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='ref_coins',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='silver',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='silver_dust',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='valknut_tokens',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='varangian_stones',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='experience_to_next_sub_level',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='agility',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='endurance',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='intuition',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='spirit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='strength',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('sub_level', models.IntegerField()),
                ('experience_required', models.IntegerField()),
            ],
            options={
                'unique_together': {('level', 'sub_level')},
            },
        ),
    ]
