# Generated by Django 5.2.2 on 2025-08-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_coins_playerprofile_free_points_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExperienceLevel',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='experience_to_next_sub_level',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.location'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='gold_dust',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='magic_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='ref_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='silver_dust',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='valknut_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='varangian_stones',
            field=models.IntegerField(default=0),
        ),
    ]
