# Generated by Django 5.2.2 on 2025-08-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_delete_experiencelevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='experience_to_next_sub_level',
            field=models.IntegerField(default=200),
        ),
    ]
