# Generated by Django 5.2.2 on 2025-08-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_playerprofile_experience_to_next_sub_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='experience_to_next_sub_level',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='free_points',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='sub_level',
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='agility',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='endurance',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='intuition',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='spirit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
    ]
