# Generated by Django 5.2.2 on 2025-08-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_playerprofile_armor_body_playerprofile_armor_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='anti_crit_chance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='anti_dodge_chance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='armor_penetration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='counterattack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='crit_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='crit_power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='dodge_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='foresight_chance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='parry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phys_absorption_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phys_damage_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='phys_damage_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='shield_block',
            field=models.IntegerField(default=0),
        ),
    ]
