# Generated by Django 5.2.2 on 2025-08-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_playerprofile_anti_crit_chance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='damage_power_percent',
            field=models.IntegerField(default=0),
        ),
    ]
