# Generated by Django 5.2.2 on 2025-08-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_playerprofile_damage_power_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='crit_absorption_percent',
            field=models.IntegerField(default=0),
        ),
    ]
