# Generated by Django 5.2.2 on 2025-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_playerprofile_crit_absorption_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='magic_absorption_percent',
            field=models.IntegerField(default=0),
        ),
    ]
