# Generated by Django 5.2.2 on 2025-08-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('game', '0023_playerprofile_magic_absorption_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='accepts_commission',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('add', 'Пополнение'), ('subtract', 'Списание'), ('transfer', 'Перевод'), ('reward', 'Награда'), ('purchase', 'Покупка'), ('sale', 'Продажа'), ('fee', 'Комиссия'), ('bank_deposit', 'Банк: внесение'), ('bank_withdraw', 'Банк: снятие'), ('exchange_out', 'Обмен: отдано'), ('exchange_in', 'Обмен: получено')], max_length=15)),
                ('balance_after', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='game.playerprofile')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['player', 'timestamp'], name='game_curren_player__730fb8_idx'), models.Index(fields=['currency_type', 'transaction_type'], name='game_curren_currenc_839317_idx')],
            },
        ),
    ]
