# Generated by Django 5.2.2 on 2025-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_shopitem_accepts_commission_currencytransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='agility',
            new_name='agility_base',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='endurance',
            new_name='endurance_base',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='intelligence',
            new_name='intelligence_base',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='intuition',
            new_name='intuition_base',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='spirit',
            new_name='spirit_base',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='strength',
            new_name='strength_base',
        ),
        migrations.RenameField(
            model_name='playerprofile',
            old_name='wisdom',
            new_name='wisdom_base',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='agility_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='endurance_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='free_stats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='intelligence_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='intuition_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='spirit_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='strength_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='sublevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='wisdom_mod',
            field=models.IntegerField(default=0),
        ),
    ]
