# Generated by Django 5.2.2 on 2025-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_rename_agility_playerprofile_agility_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='agility_base',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='endurance_base',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='intelligence_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='intuition_base',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='spirit_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='strength_base',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='wisdom_base',
            field=models.IntegerField(default=0),
        ),
    ]
