# Generated by Django 5.2.2 on 2025-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_playerprofile_agility_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='current_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='current_mp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='max_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='max_mp',
            field=models.IntegerField(default=0),
        ),
    ]
