# Generated by Django 5.2.2 on 2025-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_playerprofile_current_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='last_online',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
