# Generated by Django 5.2.8 on 2025-11-10 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_playerprofile_last_online_alter_playerprofile_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['slot_index']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_equipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='current_durability',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='max_durability',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='game.playerprofile'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='slot_index',
            field=models.IntegerField(default=0),
        ),
    ]
