# Generated by Django 5.2.8 on 2025-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_fix_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['inventory_position']},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='slot_index',
            new_name='inventory_position',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='base_inventory_slots',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='bonus_inventory_slots',
            field=models.IntegerField(default=0),
        ),
    ]
