# Generated by Django 6.0.1 on 2026-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0032_combat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=0)),
                ("hp", models.IntegerField(default=100)),
                ("strength", models.IntegerField(default=3)),
                ("agility", models.IntegerField(default=3)),
                ("intuition", models.IntegerField(default=3)),
                ("endurance", models.IntegerField(default=3)),
                ("damage_min", models.IntegerField(default=1)),
                ("damage_max", models.IntegerField(default=5)),
                ("crit_chance", models.IntegerField(default=5)),
                ("dodge_chance", models.IntegerField(default=5)),
                ("armor", models.IntegerField(default=0)),
                ("xp_reward", models.IntegerField(default=10)),
                ("coin_reward", models.IntegerField(default=1)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="monsters/"),
                ),
            ],
        ),
    ]
