# Generated by Django 6.0.1 on 2026-02-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0033_monster"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="hp_restore",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="mp_restore",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="hp_regen_rate",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="mp_regen_rate",
            field=models.IntegerField(default=100),
        ),
    ]
