# Generated by Django 6.0.1 on 2026-02-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0034_item_hp_restore_item_mp_restore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="equipped_slot",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_quest",
            field=models.BooleanField(default=False),
        ),
    ]
