# Generated by Django 6.0.1 on 2026-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0035_inventoryitem_equipped_slot_item_is_quest"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="last_resource_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
