# Generated by Django 6.0.1 on 2026-02-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0036_playerprofile_last_resource_update"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monster",
            old_name="xp_reward",
            new_name="xp_reward_min",
        ),
        migrations.AddField(
            model_name="monster",
            name="xp_reward_max",
            field=models.IntegerField(default=20),
        ),
    ]
